name: custom_cursor
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  plugin_platform_interface: ^1.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  plugin:
    platforms:
      web:
        pluginClass: CustomCursorPlugin
        fileName: custom_cursor_web.dart
      # android:
      #   package: com.example.custom_cursor
      #   pluginClass: CustomCursorPlugin
      # ios:
      #   pluginClass: CustomCursorPlugin
      macos:
        pluginClass: CustomCursorPlugin

